version: '3.9'
services:
  frontend:
    image: dentapp:latest
    container_name: frontend
    ports:
      - 8086:80
    environment:
      VITE_SERVER_URL: http://212.112.123.118:8082/api
    networks:
      - aksoft_default

networks:
  aksoft_default:
    driver: bridge