version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    environment:
      HOST: $HOST
      SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

    steps:
      - checkout
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
      - run:
          name: Build Docker Image
          command: docker build -t estetic-clinic-next .
      - run:
          name: Deploy to Remote Host
          command: |
            ssh -i ~/.ssh/id_rsa user@$HOST 'docker-compose -f docker-compose.yml up -d'
